version: "2"

networks:
  zeebe_network:

volumes:
  zeebe_data:
  zeebe_elasticsearch_data:

services:
  zeebe:
    image: camunda/zeebe:0.17.0
    #    environment:
    #      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "26501:26501"
    volumes:
      - zeebe_data:/usr/local/zeebe/bin/data
  operate:
    image: camunda/operate:latest
    ports:
      - "8080:8080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=zeebe
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - zeebe_elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.7.1
    ports:
      - "5601:5601"
