version: "2"

services:
  db:
    image: oscarfonts/h2
    container_name: zeebe_db
    ports:
      - "1521:1521"
      - "81:81"
    networks:
      - zeebe-network
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.17.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - SIMPLE_MONITOR_EXPORTER_JDBC_URL=jdbc:h2:tcp://db:1521/zeebe-monitor
    ports:
      - "26500:26500"
      - "5701:5701"
    volumes:
      - ./zeebe-simple-monitor-exporter-0.13.0.jar:/usr/local/zeebe/lib/zeebe-simple-monitor-exporter.jar
      - ./zeebe-hazelcast-exporter-0.2.0.jar:/usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar
      - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe-network
    depends_on:
      - db
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - spring.datasource.url=jdbc:h2:tcp://db:1521/zeebe-monitor
      - io.zeebe.monitor.connectionString=zeebe:26500
      - io.zeebe.monitor.hazelcast.connection=zeebe:5701
    ports:
      - "8080:8080"
    depends_on:
      - db
      - zeebe
    restart: always
    networks:
      - zeebe-network
networks:
  zeebe-network:
    driver: bridge
