name: "Test-on-Camunda-Cloud"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run build
          npm run test:integration
    env:
      ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
      ZEEBE_CLIENT_ID: $ {{ secrets.ZEEBE_CLIENT_ID }}
      ZEEBE_AUTHORISATION_URL: ${{ secrets.ZEEBE_AUTHORISATION_URL }}
      ZEEBE_CLIENT_SECRET: ${{ secrets.ZEEBE_CLIENT_SECRET }}
