name: test
on:
  push:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      zeebe:
        image: camunda/zeebe:0.24.2
        ports:
          - 26500:26500
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.0.0
      - run: npm install
      - run: npm install -g typescript ts-node jest
      - run: npm run test:integration
